### ISSUE TITLE
On BigchainDB 0.8 release upgrade dependency in setup.py

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bdb-transaction-cli#14]
Timestamps are removed in the future 0.8 release.
The CLI's bigchaindb dependency needs to be updated in that regard.

//cc'ed alberto for hackathon

**Comment by libscott** [comment]
Good point.

I have a PR for timestamp removal: https://github.com/bigchaindb/bdb-transaction-cli/pull/13
